#!/usr/bin/env python3

import importlib
import configparser as cp


# _prox_info: {} = {}
# try:
#    _cp: cp.ConfigParser = cp.ConfigParser()
#    _cp.read("conf/prox_runner.ini")
#    _prox = _cp["PROX_TO_RUN"]["PROCS_NAME"].split("|")
#    for p in _prox:
#       _prox_info[p] = _cp["PROX_INFO"][p].split("|")
# except Exception as e:
#    print(e)
#    exit(1)

# -- try to run & mon procs --
def start_prox():
   for pname in _prox_info:
      pinfo = _prox_info[pname]
      print([pname, pinfo])
      i = importlib.import_module(pinfo[1])
      print(i)


def main():
   start_prox()
   while True:
      pass


# -- -- -- start -- -- --
if __name__ == "__main__":
   main()
