#!/usr/bin/env python3

from core.redisProxy import redisProxy
from core.classAsProcRunner import classAsProcRunner


# -- dev --
DEV_NAME = "/dev/pts/11"
REDIS_HOST = "localhost"
REDIS_PORT = 16379
# -- prod --
# DEV_NAME = "/dev/ttyUSB0"
# REDIS_HOST = "10.0.0.122"
# REDIS_PORT = 6379
# -- global --
REDIS_PWD = "Q@@bcd!234##!"


proxy: redisProxy = redisProxy(DEV_NAME, REDIS_HOST, REDIS_PORT, REDIS_PWD)
runner: classAsProcRunner = classAsProcRunner("redproxy", proxy, "run")
runner.init()
runner.run_main_loop()
