#!/usr/bin/env python3

import configparser
from core.redisProxy import redisProxy
from core.serialReader import serialReader
from core.classAsProcRunner import classAsProcRunner


conf: configparser.ConfigParser = configparser.ConfigParser()
conf.read("conf/conf.ini")

redProxy: redisProxy = redisProxy(conf, "DEV_REDIS_CONN")
# redProxy: redisProxy = redisProxy(conf)

proxy: serialReader = serialReader(conf, redProxy)
runner: classAsProcRunner = classAsProcRunner("serialReader", proxy, "run")
runner.init()
runner.run_main_loop()
