#!/usr/bin/env python3

import configparser
from core.redisProxy import redisProxy
from core.serRedBot import serRedBot
from core.classAsProcRunner import classAsProcRunner


conf: configparser.ConfigParser = configparser.ConfigParser()
conf.read("conf/conf.ini")

redProxy: redisProxy = redisProxy(conf, "DEV_REDIS_CONN")
# redProxy: redisProxy = redisProxy(conf)

proxy: serRedBot = serRedBot(conf, redProxy)
pn = f"{proxy.__class__.__name__}Runr"
runner: classAsProcRunner = classAsProcRunner(pn, proxy, "run")
runner.init()
runner.run_main_loop()
