#!/usr/bin/env python3

import setproctitle
import threading as th
import time, configparser
from core.redisProxy import redisProxy
from core.serRedBot import serRedBot
from core.debug import debug


conf: configparser.ConfigParser = configparser.ConfigParser()
conf.read("conf/ser_red_bot.ini")


IS_DEBUG: bool = debug.is_dev_box()


if IS_DEBUG:
   redProxy: redisProxy = redisProxy(conf, "DEV_REDIS_CONN")
else:
   redProxy: redisProxy = redisProxy(conf)
# -- worker thread --
serRedBotProxy: serRedBot = serRedBot(conf, redProxy)
serRedBotProxyTh: th.Thread = th.Thread(target=serRedBotProxy.run, args=())


# -- block on main file --
def main():
   serRedBotProxyTh.start()
   while True:
      time.sleep(8.0)
      print("main_loop")


# -- -- start here -- --
if __name__ == "__main__":
   setproctitle.setproctitle("serRedRunner")
   main()
